INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);

INSERT INTO projects (title, category, funding_goal, start_date, end_date)